//48武将扩展包，适用于身份场
'use strict';
game.import('character', function (lib, game, ui, get, ai, _status) {
    return {
        name: 'SNH48G',
        connect: true,
        character: {
            _48chenguanhui: ['female', 'wei', 4, ['biyue', 'guidao']],
            _48chensi: ['female', 'wei', 3, ['wushuang', 'feiying']],
            _48jiangyun: ['female', 'wei', 3, ['leiji', 'hunshang']],
            _48kongxiaoyin: ['female', 'wei', 4, ['lieren']],
            _48liyuqi: ['female', 'wei', 3, ['mingce', 'longdan']],
            _48qianbeiting: ['female', 'wei', 4, ['chongzhen', 'longdan']],
            _48wenjingjie: ['female', 'wei', 4, ['zaiqi']],
            _48wuzhehan: ['female', 'wu', 3, ['qianxun', 'qixi']],
            _48yuanyuzhen: ['female', 'wei', 4, ['duanliang']],
            _48xuzixuan: ['female', 'wei', 4, ['jianxiong']],
            _48zhaojiamin: ['female', 'wu', 3, ['fankui', 'tiandu']],
            _48shenzhilin: ['female', 'wu', 4, ['guicai', 'yiji']],
            _48mohan: ['female', 'wei', 3, ['jizhi', 'qicai']],
            _48sunrui: ['female', 'wei', 4, ['tiaoxin', 'tiandu']],
            _48daimeng: ['female', 'wei', 4, ['gzkongcheng', 'gzqianxun']],
            _48xujiaqi: ['female', 'qun', 3, ['qingcheng', 'duoshi']],
            _48zhangyuge: ['female', 'qun', 4, ['gzduanchang', 'gzweimu']],
            _48xuchenchen: ['female', 'qun', 3, ['leiji', 'lianying']],
            _48fengxiaofei: ['female', 'wu', 4, ['qingcheng', 'duoshi']],

            _48fengxinduo: ['female', 'qun', 3, ['zhiheng']],
            _48huangtingting: ['female', 'qun', 3, ['rende', 'yingzi']],
            _48liyitong: ['female', 'shu', 3, ['qingcheng', 'duoshi']],
            _48luting: ['female', 'qun', 3, ['biyue', 'lijian']],
            _48linsiyi: ['female', 'shu', 3, ['qingcheng', 'duoshi']],
            _48wanlina: ['female', 'shu', 3, ['paoxiao', 'longdan']],
            _48yijiaai: ['female', 'shu', 3, ['duwu', 'qishu']],
            _48jujingyi: ['female', 'qun', 3, ['liuli', 'lianying']],
            _48wuyanwen: ['female', 'shu', 3, ['qingcheng', 'duoshi']],
            _48liujiongran: ['female', 'qun', 3, ['qingcheng', 'duoshi']],

            _48feiqinyuan: ['female', 'shu', 4, ['jiang', 'luanji']],
            _48wangxiaojia: ['female', 'wu', 4, ['guanxing', 'danlao']],



            shibing1wei: ['male', 'wei', 0, [], ['unseen']],
            shibing2wei: ['female', 'wei', 0, [], ['unseen']],
            shibing1shu: ['male', 'shu', 0, [], ['unseen']],
            shibing2shu: ['female', 'shu', 0, [], ['unseen']],
            shibing1wu: ['male', 'wu', 0, [], ['unseen']],
            shibing2wu: ['female', 'wu', 0, [], ['unseen']],
            shibing1qun: ['male', 'qun', 0, [], ['unseen']],
            shibing2qun: ['female', 'qun', 0, [], ['unseen']],
        },
        characterIntro: {
            _48mohan: 'SNH48一期生，SNH48 TeamSII 副队长',
            _48sunrui: 'SNH48 TeamSII 成员，SNH48二期生',
            _48daimeng: 'SNH48 TeamSII 成员，SNH48一期生',
            _48xujiaqi: 'SNH48 TeamSII 成员，SNH48一期生',
            _48zhangyuge: 'SNH48 TeamSII 成员，SNH48一期生',
            _48xuchenchen: 'SNH48 TeamSII 成员，SNH48一期生',
            _48fengxiaofei: 'SNH48 TeamX 成员，SNH48四期生，曾经是著名SNH48黑，OLD48法人',
            _48chenguanhui: 'SNH48 TeamSII 成员，SNH48一期生',
            _48chensi: 'TeamSII 成员，SNH48一期生',
            _48jiangyun: 'TeamSII 成员，SNH48二期生',
            _48kongxiaoyin: 'TeamSII 成员，SNH48一期生',
            _48liyuqi: 'TeamSII 成员，SNH48一期生',
            _48qianbeiting: 'TeamSII 成员，SNH48一期生',
            _48wenjingjie: 'TeamSII 成员，SNH48二期生',
            _48wuzhehan: 'TeamSII 成员，SNH48一期生',
            _48yuanyuzhen:'TeamSII 成员，SNH48二期生',
            _48xuzixuan: 'TeamSII 成员，SNH48二期生',
            _48zhaojiamin: 'TeamSII 成员，SNH48一期生',
            _48shenzhilin: 'TeamSII 成员，SNH48二期生',

            _48fengxinduo: 'TeamNII 成员，SNH48二期生',
            _48huangtingting: 'TeamNII 成员，SNH48二期生',
            _48liyitong: 'TeamHII 成员，SNH48二期生',
            _48luting: 'TeamNII 成员，SNH48二期生',
            _48linsiyi: 'TeamHII 成员，SNH48二期生',
            _48wanlina: 'TeamHII 成员，SNH48二期生',
            _48yijiaai: 'TeamNII 成员，SNH48二期生',
            _48jujingyi: 'SNH48 明星殿堂 成员，SNH48二期生',
            _48wuyanwen: 'TeamHII 成员，SNH48三期生',
            _48liujiongran: 'TeamC 成员，SNH48三期生',

            _48feiqinyuan: 'TeamHII 成员，SNH48五期生',
            _48wangxiaojia: 'TeamX 成员，SNH48四期生',
        },
        characterFilter: {
            _48: function (mode) {
                return mode != '_48';
            }
        },
        card: {
            
        },
        translate: {
            _48chenguanhui: '陈观慧',
            _48chensi: '陈思',
            _48jiangyun: '蒋芸',
            _48kongxiaoyin: '孔肖吟',
            _48liyuqi: '李宇琪',
            _48qianbeiting: '钱蓓婷',
            _48wenjingjie: '温晶婕',
            _48wuzhehan: '吴哲晗',
            _48yuanyuzhen: '袁雨桢',
            _48xuzixuan: '徐子轩',
            _48zhaojiamin: '赵嘉敏',
            _48shenzhilin: '沈之琳',
            _48mohan: '莫寒',
            _48sunrui: '孙芮',
            _48daimeng: '戴萌',
            _48xujiaqi: '许佳琪',
            _48zhangyuge: '张语格',
            _48xuchenchen: '徐晨辰',
            _48fengxiaofei: '冯晓菲',
            _48fengxinduo: '冯薪朵',
            _48huangtingting: '黄婷婷',
            _48liyitong: '李艺彤',
            _48luting: '陆婷',
            _48linsiyi: '林思意',
            _48wanlina: '万丽娜',
            _48yijiaai: '易嘉爱',
            _48jujingyi: '鞠婧祎',
            _48wuyanwen: '吴燕文',
            _48liujiongran: '刘炅然',
        },
    };
});
